# Generated by Django 6.0.4 on 2026-04-22 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('image_url', models.URLField()),
                ('sprite_url', models.URLField(blank=True)),
                ('primary_type', models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fuego'), ('water', 'Agua'), ('electric', 'Eléctrico'), ('grass', 'Planta'), ('ice', 'Hielo'), ('fighting', 'Lucha'), ('poison', 'Veneno'), ('ground', 'Tierra'), ('flying', 'Volador'), ('psychic', 'Psíquico'), ('bug', 'Bicho'), ('rock', 'Roca'), ('ghost', 'Fantasma'), ('dragon', 'Dragón'), ('dark', 'Siniestro'), ('steel', 'Acero'), ('fairy', 'Hada')], db_index=True, max_length=20)),
                ('secondary_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('fire', 'Fuego'), ('water', 'Agua'), ('electric', 'Eléctrico'), ('grass', 'Planta'), ('ice', 'Hielo'), ('fighting', 'Lucha'), ('poison', 'Veneno'), ('ground', 'Tierra'), ('flying', 'Volador'), ('psychic', 'Psíquico'), ('bug', 'Bicho'), ('rock', 'Roca'), ('ghost', 'Fantasma'), ('dragon', 'Dragón'), ('dark', 'Siniestro'), ('steel', 'Acero'), ('fairy', 'Hada')], db_index=True, max_length=20, null=True)),
                ('hp', models.PositiveSmallIntegerField()),
                ('attack', models.PositiveSmallIntegerField()),
                ('defense', models.PositiveSmallIntegerField()),
                ('special_attack', models.PositiveSmallIntegerField()),
                ('special_defense', models.PositiveSmallIntegerField()),
                ('speed', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(choices=[('party', 'Party'), ('box', 'PC Box')], db_index=True, max_length=10)),
                ('position', models.PositiveSmallIntegerField()),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='roster_entry', to='roster.pokemon')),
            ],
            options={
                'ordering': ['location', 'position'],
                'constraints': [models.UniqueConstraint(fields=('location', 'position'), name='unique_position_per_location'), models.CheckConstraint(condition=models.Q(models.Q(('location', 'party'), ('position__gte', 1), ('position__lte', 6)), models.Q(('location', 'box'), ('position__gte', 1)), _connector='OR'), name='valid_position_for_location')],
            },
        ),
    ]
